#!/bin/bash

hex()
{
  openssl rand -hex 8
}

SIABUSER=${SIABUSER:-ImLazyAutoGenerateUsername}
SIABUSERID=${SIABUSERID:-1000}
SIABPASS=${SIABPASS:-ImLazyAutoGeneratePassword}

#if [ -z "$(getent group ${SIAB_GROUP})" ]; then
# /usr/sbin/groupadd -g ${SIAB_GROUPID} ${SIAB_GROUP}
#fi

if [ "${SIABUSER}" == "ImLazyAutoGenerateUsername" ]; then
  SIABUSER=$(hex)
  echo "Autogenerated usernme: ${SIABUSER}"
fi

if [ -z "$(getent passwd ${SIABUSER})" ]; then
  useradd -u ${SIABUSERID} -G users,sudo -s /bin/bash -m -d /home/${SIABUSER} ${SIABUSER}
  if [ "${SIABPASS}" == "ImLazyAutoGeneratePassword" ]; then
    SIABPASS=$(hex)
    echo "Autogenerated password for user ${SIABUSER}: ${SIABPASS}"
  fi
  echo "${SIABUSER}:${SIABPASS}" | chpasswd
  unset SIABPASS
fi

/etc/init.d/shellinabox start

exec /app/dockerwait.static
